language: clojure
lein: lein2
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libgfortran3
install: lein2 modules install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: lein2 modules test
